### ISSUE TITLE
the samles -> 404

### ISSUE THREAD

**Issue by jkleiser** [giuseppemag/MonadicReact#10]
When I click the link "the samples", pointing to https://raw.githubusercontent.com/giuseppemag/MonadicReact/master/samples, my Safari downloads a small file samples.dms, containing the text "404: Not Found".

**Comment by RonaldDijks** [comment]
Hello @jkleiser, thank you for submitting your issue. I fixed the hyperlink so that it points to the correct page again.

Have a good day!
